version: '3.4'

networks:
  rag:
    name: rag
    driver: bridge
    ipam:
      config:
        - subnet: 182.18.0.0/16

services:
  messagebrokerserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      rag:
        ipv4_address: 182.18.0.16
      