version: '3.4'

networks:
  baas:
    external: true
    
services:
  messagebrokerserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      baas:
        ipv4_address: 172.18.0.16